Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "hbase-solr-indexer"
  config.vm.network :private_network, ip: "192.168.1.44"
  config.vm.network "forwarded_port", guest: 8983, host: 8983 # Solr

  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "shell", path: "provision.sh", env: {
    # "STORAGE_ACCT" => "change.me",
    # "STORAGE_ACCT_KEY" => "change.me",
    # "DEF_FS_CNT" => "change.me",
    # "RESULTS_CNT" => "change.me",
    "IS_MASTER" => 1}
end
